CREATE TABLE TIP_GROUP (
    TIP_GROUP_ID 			INTEGER PRIMARY KEY AUTOINCREMENT
    , PARENT_TIP_GROUP_ID INTEGER
    , TIP_GROUP_NAME      TEXT
    , REMARK        TEXT
    , SORT_NO       NUMERIC
    , DEL_FLAG      TEXT
    , CREATE_DTTM   TEXT
    , UPDATE_DTTM   TEXT
);
CREATE TABLE TIP (
	TIP_ID 		INTEGER	PRIMARY KEY AUTOINCREMENT
    , TIP_GROUP_ID      INTEGER
    , TIP_TITLE         TEXT
	, TIP_CONTENT		TEXT
	, TIP_CONTENT_FILE	BLOB
	, REMARK			TEXT
    , SORT_NO       NUMERIC
    , DEL_FLAG      TEXT
    , CREATE_DTTM   TEXT
    , UPDATE_DTTM   TEXT
);	