CREATE TABLE TIP_HEADER (
    TIP_ID 			INTEGER PRIMARY KEY AUTOINCREMENT
    , PARENT_TIP_ID INTEGER
    , TIP_NAME      TEXT
    , REMARK        TEXT
    , SORT_NO       INTEGER
    , DEL_FLAG      TEXT
    , CREATE_DTTM   TEXT
    , UPDATE_DTTM   TEXT
);
CREATE TABLE TIP_DETAIL (
	TIP_DETAIL_ID 		INTEGER	PRIMARY KEY AUTOINCREMENT
	, TIP_CONTENT		TEXT
	, TIP_CONTENT_FILE	BLOB
	, REMARK			TEXT
    , SORT_NO       INTEGER
    , DEL_FLAG      TEXT
    , CREATE_DTTM   TEXT
    , UPDATE_DTTM   TEXT
);	